language: cpp

dist: trusty
sudo: required

branches:
  only:
    - develop

matrix:
  include:
    - os: linux
      compiler: gcc
      addons:
        apt:
          sources: ['ubuntu-toolchain-r-test']
          packages: ['g++-5']
      env: COMPILER=g++-5

    - os: linux
      compiler: gcc
      addons:
        apt:
          sources: ['ubuntu-toolchain-r-test']
          packages: ['g++-6']
      env: COMPILER=g++-6

    - os: linux
      compiler: clang
      addons:
        apt:
          sources: ['ubuntu-toolchain-r-test', 'llvm-toolchain-trusty-3.9']
          packages: ['clang-3.9']
      env:
          - COMPILER=clang++-3.9
          - CXXFLAGS='-std=c++11 -O2'

script:
  - scons CXX=$COMPILER RELEASE=1
  - ./build/runtests
  - cat build/src/buildinfo.h

before_install:
  - sudo apt-get update -qq
  - sudo apt-get install -y libcpputest-dev

git:
    depth: 3
