language: cpp

dist: trusty
sudo: required
os: linux

branches:
  only:
    - develop

git:
    depth: 3

before_install:
  - sudo apt-get update -qq
  - sudo apt-get install -y libcpputest-dev

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-5
      - g++-6

matrix:
  include:
    - env:
      - COMPILER=g++-5 PYVERSION=2.7

    - env:
      - COMPILER=g++-6 PYVERSION=2.7

    - env:
      - COMPILER=g++-5 PYVERSION=3.4m

    - env:
      - COMPILER=g++-6 PYVERSION=3.4m

script:
  - scons CXX=$COMPILER PYVERSION=$PYVERSION lib
  - cat build/src/buildinfo.h
  - scons CXX=$COMPILER PYVERSION=$PYVERSION test
  - ./build/runtests
