language: cpp

os: linux

branches:
    only:
        - develop

script:
    - scons
    - ./build/runtests

compiler:
    - clang
    - gcc

before_install:
    - sudo apt-get update -qq
    - sudo apt-get install -y python3-dev python-dev

python:
    - 2.7
    - 3.4
    - 3.5
    - 3.6

git:
    depth: 3
