language: cpp

dist: trusty
sudo: required

branches:
  only:
    - develop

matrix:
  include:
    - os: linux
      compiler: gcc
      addons:
        apt:
          sources: ['ubuntu-toolchain-r-test']
          packages: ['g++-5']
      env:
          - COMPILER=g++-5
          - PYVERSION=2.7

    - os: linux
      compiler: gcc
      addons:
        apt:
          sources: ['ubuntu-toolchain-r-test']
          packages: ['g++-6']
      env:
          - COMPILER=g++-6
          - PYVERSION=2.7

script:
  - scons CXX=$COMPILER PYVERSION=$PYVERSION
  - ./build/runtests
  - cat build/src/buildinfo.h
  - find /usr -name 'Python.h' -or -iname 'libpython*.so'

before_install:
  - sudo apt-get update -qq
  - sudo apt-get install -y libcpputest-dev

git:
    depth: 3
